# Generated by Django 4.1.7 on 2023-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_group_user_purpose_statement_embedding_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='amazing_kare', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
