# Generated by Django 4.2 on 2023-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_group_name_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='relaxed_heyrovsky', max_length=255),
        ),
    ]
