# Generated by Django 4.2 on 2023-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='sleepy_joliot', max_length=255),
        ),
    ]
